### ISSUE TITLE
AssertionError caused by lark-parser==0.7.2

### ISSUE THREAD

**Issue by jonhammer** [vaidik/commentjson#25]
Tested in python 2.7.

```
>>> from commentjson import commentjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jhammer/Envs/test2/lib/python2.7/site-packages/commentjson/__init__.py", line 1, in <module>
    from .commentjson import dump
  File "/Users/jhammer/Envs/test2/lib/python2.7/site-packages/commentjson/commentjson.py", line 54, in <module>
    ''', start='start')
  File "/Users/jhammer/Envs/test2/lib/python2.7/site-packages/lark/lark.py", line 226, in __init__
    self.parser = self._build_parser()
  File "/Users/jhammer/Envs/test2/lib/python2.7/site-packages/lark/lark.py", line 245, in _build_parser
    parser_conf = ParserConf(self.rules, self._callbacks, self.options.start)
  File "/Users/jhammer/Envs/test2/lib/python2.7/site-packages/lark/common.py", line 23, in __init__
    assert isinstance(start, list)
AssertionError
```

**Comment by Sreevalli961** [comment]
Traceback (most recent call last):
  File "C:\auto_fat\auto_fat_check.py", line 5, in <module>
    import commentjson
  File "C:\Python27\lib\site-packages\commentjson\__init__.py", line 1, in <module>
    from .commentjson import dump
  File "C:\Python27\lib\site-packages\commentjson\commentjson.py", line 54, in <module>
    ''', start='start')
  File "C:\Python27\lib\site-packages\lark\lark.py", line 226, in __init__
    self.parser = self._build_parser()
  File "C:\Python27\lib\site-packages\lark\lark.py", line 245, in _build_parser
    parser_conf = ParserConf(self.rules, self._callbacks, self.options.start)
  File "C:\Python27\lib\site-packages\lark\common.py", line 23, in __init__
    assert isinstance(start, list)
AssertionError




The same issue i am facing since this morning. I need to resolve this issue as soon as possible . can you help me out with this issue.

**Comment by Sreevalli961** [comment]
@jonhammer i resolved this issue . I think this step will resolve your issue also

In the commentjson.py file remove **start = 'start'**

parser = Lark('''
    ?start: value
    ?value: object
          | array
          | string
          | SIGNED_NUMBER      -> number
          | "true"             -> true
          | "false"            -> false
          | "null"             -> null
    array  : "[" [value ("," value)*] "]"
    object : "{" [pair ("," pair)*] "}"
    pair   : string ":" value
    string : ESCAPED_STRING

    COMMENT: /(#|\/\/)[^\\n]*/

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
    %ignore COMMENT
''' **,start = 'start'**)

**Comment by vaidik** [comment]
Confirm this. lark-parser==0.7.2 broke this. Wasn't a problem with 0.7.1

**Comment by vaidik** [comment]
Just made a release to fix this issue. Solution suggested by @Sreevalli961 helped. Thanks for that. :)

**Comment by Sreevalli961** [comment]
My pleasure
